# Generated by Django 3.0.4 on 2020-03-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("programmeletter", "0001_initial"), ("suspense", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="staffinteam",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="suspense.Staff"
            ),
        ),
        migrations.AddField(
            model_name="staffinteam",
            name="team_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="programmeletter.TeamName",
            ),
        ),
        migrations.AddField(
            model_name="letterdata",
            name="team_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="programmeletter.TeamName",
            ),
        ),
        migrations.AddField(
            model_name="letterdata",
            name="vehicle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="suspense.Vehicle",
            ),
        ),
    ]
