repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
    -   id: flake8
        args: [--max-line-length=80]
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--line-length=80]

-   repo: https://github.com/miki725/importanize
    rev: '0.7'
    hooks:
        - id: importanize
          language_version: python3
          args: [--verbose]
