version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'libre@hatti'
      MYSQL_DATABASE: 'librehatti'
      MYSQL_USER: 'librehatti'
      MYSQL_PASSWORD: 'libre@hatti'
    ports:
      - "3306:3306"   
    
      
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  