version: '3'

networks:
  lh:
    driver: bridge

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: 'librehatti'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    hostname: "LH_DB"
    networks:
      - lh
  web:
    build: .
    command: ["./scripts/wait-for-it.sh", "db:3306", "--", "python3", "src/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    hostname: "LH_APP"
    networks:
      - lh
