# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=400)),
                ('is_permanent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Quoted Order Note',
            },
        ),
        migrations.CreateModel(
            name='QuotedBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charges', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('totalplusdelivery', models.IntegerField()),
                ('total_tax', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('amount_received', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField()),
                ('qty', models.IntegerField(verbose_name=b'Quantity')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_debit', models.BooleanField(default=False, verbose_name=b'Non-Payment Job')),
                ('reference', models.CharField(max_length=200, verbose_name=b'Letter No.')),
                ('reference_date', models.DateField(verbose_name=b'Letter Date')),
                ('delivery_address', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Site')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('total_discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotedOrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='QuotedOrderofSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_order_session', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotedTaxesApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge_name', models.CharField(max_length=500)),
                ('surcharge_value', models.FloatField()),
                ('tax', models.IntegerField()),
                ('quoted_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.QuotedOrder')),
            ],
        ),
    ]
