# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('bills', '0001_initial'),
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedtaxesapplied',
            name='surcharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Surcharge'),
        ),
        migrations.AddField(
            model_name='quotedorderofsession',
            name='quoted_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.QuotedOrder'),
        ),
        migrations.AddField(
            model_name='quotedorderofsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.FinancialSession'),
        ),
        migrations.AddField(
            model_name='quotedordernote',
            name='quoted_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.QuotedOrder'),
        ),
        migrations.AddField(
            model_name='quotedorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Client'),
        ),
        migrations.AddField(
            model_name='quotedorder',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.AdminOrganisations'),
        ),
        migrations.AddField(
            model_name='quoteditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='quoteditem',
            name='quoted_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.QuotedOrder'),
        ),
        migrations.AddField(
            model_name='quotedbill',
            name='quoted_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.QuotedOrder'),
        ),
    ]
