# -*- coding: utf-8 -*-
# Generated by Django 3.0.4 on 2020-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedRegisters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("selected_fields", models.CharField(max_length=1000)),
            ],
        )
    ]
