"""Catalog"""
_BUYER = "Client"
_DELIVERY_ADDRESS = "Site"
_IS_DEBIT = "Non-Payment Job"
_PURCHASED_ITEMS = "Tests"
_PARENT_CATEGORY = "Lab"
_SUB_CATEGORY = "Material"
_ITEM = "Test"
_QTY = "Quantity"
_TYPE = "Type Of Work"
_COUNTRY = "Country"

"""User Configs"""
_SENDER_EMAIL = "your email"
_PASSWORD = "email password"
_RECEIVER_EMAIL = "receiver email id"

"""Group Configs"""
_ADMIN_GROUP = "group name"

"""Account Information"""
_ACCOUNT_HOLDER = "ACCOUNT HOLDER"
_NAME_OF_BANK = "Bank Name"
_BRANCH = "district"
_ONLINE_ACCOUNT = "Online Account No."
_IFSC_CODE = "IFSC Code No."
_ORG_TYPE = "Organisation"
_CUBE_TEST = "Cube Test"
_TEST_DATE = "Date of testing"

"""Reference"""
_REFERENCE = "Letter No."
_REFERENCE_DATE = "Letter Date"
_YOUR_LETTER_No = "Your letter No."
