# Generated by Django 3.0.4 on 2020-03-16 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("useraccounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_number", models.BooleanField(default=True)),
                ("is_string", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "Attributes"},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.Category",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_order_of_session", models.IntegerField()),
                ("previous_total", models.IntegerField()),
                ("new_total", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("initiator", models.CharField(max_length=50)),
                ("initiation_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_start_date", models.DateField()),
                ("session_end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="HeaderFooter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", tinymce.models.HTMLField()),
                ("footer", tinymce.models.HTMLField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "Header and Footer"},
        ),
        migrations.CreateModel(
            name="ModeOfPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=25)),
            ],
            options={"verbose_name_plural": "Modes of payment"},
        ),
        migrations.CreateModel(
            name="NonPaymentOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=200, verbose_name="Letter No."),
                ),
                ("reference_date", models.DateField(verbose_name="Letter Date")),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Site"
                    ),
                ),
                ("item_type", models.CharField(max_length=200)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("price_per_unit", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    mptt.fields.TreeForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.Category",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccounts.AdminOrganisations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_debit",
                    models.BooleanField(default=False, verbose_name="Non-Payment Job"),
                ),
                (
                    "reference",
                    models.CharField(max_length=200, verbose_name="Letter No."),
                ),
                (
                    "reference_date",
                    models.DateField(blank=True, null=True, verbose_name="Letter Date"),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Site"
                    ),
                ),
                ("date_time", models.DateField(auto_now_add=True)),
                ("purchase_order_time", models.TimeField(auto_now_add=True)),
                ("total_discount", models.IntegerField(default=0)),
                ("tds", models.IntegerField(default=0)),
                ("cheque_dd_number", models.CharField(blank=True, max_length=50)),
                (
                    "cheque_dd_date",
                    models.DateField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "mode_of_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.ModeOfPayment",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccounts.AdminOrganisations",
                    ),
                ),
                (
                    "type_of_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useraccounts.OrganisationType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Surcharge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_name", models.CharField(max_length=200)),
                ("value", models.FloatField()),
                ("taxes_included", models.BooleanField(default=False)),
                ("tax_effected_from", models.DateField(null=True)),
                ("tax_valid_till", models.DateField(null=True)),
                ("Remark", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TaxesApplied",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surcharge_name", models.CharField(max_length=500)),
                ("surcharge_value", models.FloatField()),
                ("tax", models.IntegerField()),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.PurchaseOrder",
                    ),
                ),
                (
                    "surcharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Surcharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurchargePaid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "surcharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Surcharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialCategories",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher", models.BooleanField(default=False)),
                ("tax", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestSurchargeChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_value", models.IntegerField()),
                ("new_value", models.IntegerField()),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.ChangeRequest",
                    ),
                ),
                (
                    "surcharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.TaxesApplied",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("cancelled", models.BooleanField(default=False)),
                ("request_response", models.DateField(null=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.ChangeRequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_per_unit", models.IntegerField()),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                ("price", models.IntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.PurchaseOrder",
                    ),
                ),
            ],
            options={"verbose_name": "Tests", "verbose_name_plural": "Tests"},
        ),
        migrations.CreateModel(
            name="NonPaymentOrderOfSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("non_payment_order_of_session", models.IntegerField()),
                (
                    "non_payment_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.NonPaymentOrder",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.FinancialSession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.mCategory",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="changerequest",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.FinancialSession",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.Unit",
            ),
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Attributes",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.Product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_charges", models.IntegerField()),
                ("total_cost", models.IntegerField()),
                ("totalplusdelivery", models.IntegerField()),
                ("total_tax", models.IntegerField()),
                ("grand_total", models.IntegerField()),
                ("amount_received", models.IntegerField()),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.PurchaseOrder",
                    ),
                ),
            ],
        ),
    ]
