# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonpaymentorderofsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.FinancialSession'),
        ),
        migrations.AddField(
            model_name='nonpaymentorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Client'),
        ),
        migrations.AddField(
            model_name='mcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mCategory'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.FinancialSession'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Unit'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Attributes'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PurchaseOrder'),
        ),
    ]
